### ISSUE TITLE
Support for "anonymizeIp" option in Google Analytics?

### ISSUE THREAD

**Issue by alanorth** [chiiya/haven#29]
I love your simple injection implementation. How can I set the `anonymizeIp` option, though? Normally I add this to my analytics call:

```
ga('send', 'pageview', {
  'anonymizeIp': true
});
```

Is it enough to add it to the options array? I tried this but I'm not sure if it's working:

```
<script>
    Haven.create({
        services: [
            {
                name: 'google-analytics',
                purposes: ['analytics'],
                type: 'google-analytics',
                inject: true,
                options: {
                    id: 'BLAH',
                    anonymizeIp: true,
                }
            }
        ]
    });
</script>
```

**Comment by chiiya** [comment]
Hello @alanorth,
Thank you for your question.

The feature should be enabled by default, but it can be customized using the `anonymizeIp` option, as you've done. You can check out the relevant bit of source code [here](https://github.com/chiiya/haven/blob/951f93b4d6491ccec9f04b4dc0744a7ae5b51698/src/services/google-analytics.ts#L76). Haven will create the `ga` instance, set the `anonymizeIp` option when enabled, and _then_ send the `pageview` event. 

Let me know if this helps!

**Comment by alanorth** [comment]
Ah that's fantastic. I didn't even think to check the code, but I see it now! Thanks for the excellent package. So simple, lightweight, and with the perfect amount of customizability.
