### ISSUE TITLE
How to configure notification style?

### ISSUE THREAD

**Issue by alanorth** [chiiya/haven#32]
The [docs](https://chiiya.github.io/haven/cookie-notification.html) mention configuring the notification style, but doesn't give an example. Neither of these seem to work:

```
<script>
Haven.create({
    notification: {
        policyUrl: "blah.com",
        background: '#428bca',
        textColor: '#ffffff',
        style: {
            background: '#428bca',
            textColor: '#ffffff',
        },
    },
...
});
</script>
```

Thanks!

Edit: I saw in the [cookie preferences docs](https://chiiya.github.io/haven/cookie-preferences.html) that we need to use `styles` (plural) instead of `style`. I tried this for the notification and it works. Cheers!

**Comment by chiiya** [comment]
Thanks for the notice! I fixed the documentation.
