### ISSUE TITLE
Cookie preferences instantiation only at page load

### ISSUE THREAD

**Issue by Grsmto** [chiiya/haven#98]
Hi,

The cookie preference is only instanciated at page load, meaning that if you use the plugin with client side routing (like with React or any other framework) it doesn't work.

The workaround I found is to do the following:

```js
const haven = Haven.getInstance();

if (haven) {
  // @ts-ignore
  haven.cookiePreferences.init();
}
```

Of course that's an ugly hack and I think there could be an API for that!

Thanks!

**Comment by chiiya** [comment]
Hey,

I've added getters for the preferences and notification components in the most recent release, see [v0.6.2](https://github.com/chiiya/haven/releases/tag/v0.6.2)

```js
const haven = Haven.create(...);
haven.preferences.init();
haven.notification.init();
```

Let me know if this works for your use case.

Generally, this is something I'm aiming to improve in a rewrite of the library I'm working on right now, which will be modular and renderless by default, meaning you can use any custom UI you want and let the library handle all of the logic for cookies and service injection by using its APIs (essentially a store it exposes). Here's how that would work in combination with Svelte for example: 

_Notification.svelte_
```svelte
<script lang="ts">
  import type { AnshinStore } from '@anshin/types';

  export let store: AnshinStore;

  function acceptAll() {
    store.commit('ENABLE_ALL_COOKIES');
  }
</script>
```

_Preferences.svelte_
```svelte
<script lang="ts">
  import type { AnshinStore } from '@anshin/types';
  import { hidePreferences } from '../store';

  export let store: AnshinStore;

  const consent = store.state.consent;

  function setAnalytics(event: Event) {
    consent.set({ ...$consent, analytics: event.target.checked });
  }

  function setMarketing(event: Event) {
    consent.set({ ...$consent, marketing: event.target.checked });
  }

  function setConsent() {
    consent.set({
      ...$consent,
      functional: true,
      analytics: !!$consent.analytics,
      marketing: !!$consent.marketing,
    });
    hidePreferences();
  }
</script>
```

**Comment by Grsmto** [comment]
Great stuff!

Closing this issue since this is now solved, thanks again!
